# ==============================================================================
# Environment Configuration
# ==============================================================================
# Shell configuration (Nushell for cross-platform compatibility)

set shell := ["nu", "-c"]
set windows-shell := ["nu", "-c"]

# ==============================================================================
# Project Configuration
# ==============================================================================

cli := "./envctl.nu"

# ==============================================================================
# Help
# ==============================================================================

[doc('Show help')]
default: help

[doc('List all commands')]
help:
    @just --list --unsorted --list-submodules

# ==============================================================================
# Development
# ==============================================================================

[doc('Install dependencies')]
[group('Development')]
deps:
    @echo "🔧 Installing tools..."
    @echo "✅ Dependencies installed!"

[doc('Format code')]
[group('Development')]
fmt:
    @echo "✨ Formatting code..."
    just --fmt --unstable
    @echo "✅ Code formatted!"

[doc('Run linters')]
[group('Development')]
lint *args:
    @echo "🔍 Running linters..."
    @echo "✅ Linting complete!"

[doc("Run tests")]
[group("Development")]
test *args:
    @echo "Running tests..."
    nu run_tests.nu {{ args }}

[doc("Run cli")]
[group("Development")]
run *args:
    @echo "🚀 Running {{ cli }}..."
    nu {{ cli }} {{ args }}

[doc('Install envctl globally')]
[group('Development')]
install *args:
    @echo "Installing envctl..."
    nu install.nu {{ args }}

[doc('Reload autoload hook (dev — sources from repo, sets ENVCTL_HOME to repo dir)')]
[group('Development')]
reload:
    @echo "🔄 Installing envctl autoload hook..."
    $"# envctl dev hook — generated by just reload\n$env.ENVCTL_HOME = '($env.PWD | path expand)'\nsource '($env.PWD | path expand | path join envctl.nu)'\n" | save --force ($nu.vendor-autoload-dirs | last | path join "envctl_loader.nu")
    @open ($nu.vendor-autoload-dirs | last | path join "envctl_loader.nu") | table --collapse

[doc("Remove artifacts")]
[group('Development')]
clean:
    @echo "🧹 Cleaning..."
    @echo "✅ Cleaned!"

# ==============================================================================
# Documentation
# ==============================================================================

[group: 'Documentation']
mod docs 'misc/justfiles/docs.just'
